services:
 
  - type: web
   
    name: pet-shop
   
    runtime: node
    
    plan: free
    
    buildCommand: "npm install"
    
    startCommand: "npm start"
   
    autoDeploy: true
    
    envVars:
     
      - key: NODE_ENV
        value: "production"
   
      - key: MONGO_URI
        sync: false
    
     # - key: JWT_SECRET
     #   sync: true
     
     # - key: JWT_EXPIRES_IN
     #   value: "1d"
     
   #   - key: BCRYPT_SALT_ROUNDS
    #    value: "10" 